version: "3"

services:

  v1:
    build:
      dockerfile: Dockerfile
      context: ./src/PaePae.Test.AspNetCore.WebApi.MultiplePaths.MultipleApps.V1
    expose:
      - 80
    
  v2:
    build:
      dockerfile: Dockerfile
      context: ./src/PaePae.Test.AspNetCore.WebApi.MultiplePaths.MultipleApps.V2
    expose:
      - 80

  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf/:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - v1
      - v2
